### PR TITLE
update to allow graphql 10

### PR DESCRIPTION
**Pull request by aruberto**

### CODE REVIEW

**Comment by aruberto** [comment]
Those tests are failing because parseValue in GraphQLScalarType now does a isNullish check before calling the parser.

https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L336

Therefore null and undefined never reach the parseValue functions defined in GraphQLDate, GraphQLTime and GraphQLDateTime

**Comment by excitement-engineer** [comment]
Thanks for your PR!

Thanks for investigating why the tests failed. It does seem that the behaviour has changed in the newest version of graphql-js. Do you want to update the tests to reflect the new behaviour?

**Comment by aruberto** [comment]
@excitement-engineer I've updated the null and undefined test cases 

(some flow checks are failing, but getting same flow errors without my changes).

**Comment by excitement-engineer** [comment]
Thanks! The flow type definitions seem to have changed as well in this version of graphql. I will take a look at it tomorrow, hopefully it will be an easy fix:)

**Comment by aruberto** [comment]
One issues is that the value of a float node should be a string

```
export type FloatValueNode = {
  kind: 'FloatValue';
  loc?: Location;
  value: string;
};
```

but in test we are passing a number

```
    const invalidLiteralFloat = {
      kind: Kind.FLOAT, value: 5
    }
```

**Comment by excitement-engineer** [comment]
Awesome, the flow check is passing! Thanks a lot for your help:)

**Pull request merged**
